# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:
    cmds:
      - cd ./todoServer ; go run main.go & 
      - cd ./userService ; go run main.go & 
      - cd ./frontend ; npm start

  up:
    cmds:
      - docker-compose up

  proto:
    cmds:
      - protoc --go_out=./pb/ --go_opt=paths=source_relative --go-grpc_out=./pb/ --go-grpc_opt=paths=source_relative proto/*.proto
        # protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative calculator.proto
  grpc:
    cmds:
      - echo "grpc client evans"
      - evans --host localhost --port 9000 -r repl

  grpcurl:
    cmds:
      - grpcurl -plaintext localhost:9000  LoggerService.SayHello